- hosts: all
  become: true

  tasks:
    - name: Update all the packages
      yum:
        name: '*'
        state: latest

    - name: Install pip
      yum:
        name: python3-pip
        state: present

    - name: Download VirtualBox installer script
      get_url:
        url: https://download.virtualbox.org/virtualbox/7.1.4/VirtualBox-7.1.4-165100-Linux_amd64.run
        dest: /tmp/VirtualBox.run

    - name: Make the installer script executable
      file:
        path: /tmp/VirtualBox.run
        mode: '0755'

    - name: Install required packages for building kernel modules
      yum:
        name: kernel-devel kernel-headers dkms elfutils-libelf-devel gcc make perl
        state: present

    - name: Run VirtualBox installer script
      command: bash /tmp/VirtualBox.run
      become: true

    - name: Update all the packages
      yum:
        name: '*'
        state: latest

    - name: Install Development tools
      command: dnf groupinstall "Development Tools" -y
      become: true

    - name: Rebuild the VirtualBox kernel modules
      command: /sbin/vboxconfig

    - name: Install utilities for Vagrant
      command: yum install -y yum-utils shadow-utils

    - name: Add the Vagrant repository
      command: yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo

    - name: Install Vagrant
      command: yum -y install vagrant

    - name: Install git
      shell: yum install -y git
      become: true

    - name: Create directory for the base VM
      file:
        path: "/tmp/ova_directory"
        state: directory
        mode: '0755'

    - name: Download the Wazuh virtual machines repository
      git:
        repo: "{{ wvm_repository }}"
        version: "{{ wvm_branch }}"
        dest: "/tmp/wazuh-virtual-machines"
      register: clone_result
      retries: 6
      delay: 10
      until: clone_result is success

    - name: Create base box
      shell: "./generate_base_box.sh"
      args:
        chdir: "/tmp/wazuh-virtual-machines/ova/workflow_scripts"

    - name: Add the created box
      shell: "vagrant box add --name al2023 /tmp/wazuh-virtual-machines/ova/workflow_scripts/al2023.box"

    - name: Deploy the VM using Vagrant
      shell: "vagrant up"
      args:
        chdir: "/tmp/wazuh-virtual-machines/ova/workflow_scripts"
    
    - name: Execute Python script in the VM
      shell: "vagrant ssh -c 'sudo python3 /tmp/ova_directory/ova_configurer.py --wia_branch {{ wia_branch }} --repository {{ repository }} --debug {{ debug}}'"
      args:
        chdir: "/tmp/wazuh-virtual-machines/ova/workflow_scripts"

    - name: Stop the VM
      shell: "vagrant halt"
      args:
        chdir: "/tmp/wazuh-virtual-machines/ova/workflow_scripts"

    # - name: Take the VM name
    #   shell: VBoxManage list vms | grep -o '"[^"]*"' | tr -d '"'
    #   register: vm_name_output

    - name: Configure VM network in VirtualBox
      shell: |
        vboxmanage modifyvm ova_base --nic2 hostonly
        vboxmanage modifyvm ova_base --cableconnected2 on

    - name: Export the VM to OVA
      shell: "vboxmanage export ova_base --output /home/ec2-user/{{ filename_ova }}"
